apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: dev
spec:
  encryptedData:
    password: AgAQYMnjMOTUJnu01kfteP8fGFUzl4ZMbDVaK3Lv0wTC+ldMxS1kFxysD+zaW6S9mYolb69GwlzxSWzhF5uUx7ZBHpR5lsQPDEj35V6ExCljwZRLWs68a3CjIzaqSP5SvhiA7bC6WF30kZFBvf8lD0p1N3s3LdOEl6XkbwdOu4U3dsBN1lOddy/aa8xnqQU2J31gVGo7ue5U1DlVRjHqipf0YLXvZ/wyJaQbv+caQwj2dOgq2k59aLQT8J1f7pxMAKi8DeJ1jzbuIEjeaEuFWysZmxL2fX9BGHOoP8dhLRtByO982/gWGCajuO12NLPL2rukAJ6Ggaga5ND3e4aGgFWoeeP9wIi8ZZJ9cNUq/mFI13T9EwQrjOAMoCEVDBIwfQ/5jwXozVaue5plLmKiQ5rA//WEnemHXbETJIZ7cTyN4ReCOxAySvECTsQA6PYF4R3QBySuNNBW7Rj8TA0Hg1iC/ew0ZuAcJ1ghHTuLN8Czmink+BtDm0aYJmGRIaaUAt3Q7kOiwrlFxagSdPYVIRLDv457Foq22f+BFgnKTCAhJaIYmWYcOhf+7l5HFcEMOrH94t5bedf0eXFsr+qj6uUxf7ZGMqdnyqint80Wgh3xrKOdwG5ZRRF5WDJyn+1CsSmU0H13Uqm3YzuouGxNZJNNzX4KMaWdeWSflYLkUwjPL96XtBbdOZx1r2Nh+UA7SASe1u3XdA==
    user: AgAgzHS2SP7nSQX/LtfnzxtUycRTNa4FFSYSD5X/kCV89UuZjfX03OpXKV05KOXZOUM4jjbGX5RJRKh9Kq8LPoenRlAf/v4GGG48LTXDMCXywFLfLVoW8j92YECGzmYWsPpVJV6y10yZCUSxWOOC2UkTIojDniyOkCdN9bmgk1NuOCntO11MqWFGXrK1E7srd4UdtLi1GexEXx3mEgTBAk1Vtr1YifRcefvQ8Qfx3VC2AMTAUjrJ5mg+Qezyu44ZbYE8K6VsyzEYoFKRHBUqtKDgNjBmu1QupJioX8Sbl9w5H+mb5ZL1aSVvf0Sy/APVcps7RkwrNvZ90EMBmOMPLejbkO4s2K+sh5Po4LijaaVqNGClc+YXqWFN2b6dw3jYSoHchi6C6Q3fAr8qa6EFU+4fAyEg6hdqCglxVP45pX6t9WoxWi09sfu7f1VlUqtWwosZuRqv4YSfA9+amLAmm45UPxK3Dj3aNlcYsb0UcghZSubbVm2ovkX3bmHoH+8/4yalIF6yA9IYgNX6etNilwHnVkqZdqNnMDtCwy9EWunpme/H6tEYypdXdgOXWV4NDe8Q2jBqTc6EJNWK5BUc9PEHNcWvpXljtRCo/whVcFsdUnINJh1Li1bLvHJMFacyOaVodq5zN7RAlkaB1Omxt1y4RNjNguNQ5ZRPT/lzDdRtRiKuKaO74ac7mrnLDb5XjQAIWuLBQg==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: dev
status: {}

